### ISSUE TITLE
Ajouter le raccourci NVDA + S pour désactiver la parole ?

### ISSUE THREAD

**Issue by juliemoynat** [twogrey/NVDA-cheatsheet#1]
Bonjour,

Dans la fiche mémo, il y a le raccourci NVDA + Maj + S qui permet de mettre en veille pour l'application en cours. Il me semble intéressant d'avoir également en tête le raccourci NVDA + S qui permet de désactiver la parole : très très utile quand il nous casse les oreilles ou quand on partage un écran avec d'autres personnes :-)

**Comment by twogrey** [comment]
Bonjour Julie,

Merci de ton retour. Tu as raison, j'ajoute ça à ma todo :-)

**Comment by twogrey** [comment]
Ajouté ;-) [ef5240d](https://github.com/twogrey/NVDA-cheatsheet/commit/ef5240d8d76dec4bfcb5bf5e6c233b250e03af97)

**Comment by juliemoynat** [comment]
Super ! Merci !
